// Keyword -> Shopify Standard Product Taxonomy path. Longest keyword wins.
export const TAXONOMY: Array<[string, string]> = [
	["tank top", "Apparel & Accessories > Clothing > Shirts > Tank Tops"],
	["t-shirt", "Apparel & Accessories > Clothing > Shirts > T-Shirts"],
	["tshirt", "Apparel & Accessories > Clothing > Shirts > T-Shirts"],
	["tee", "Apparel & Accessories > Clothing > Shirts > T-Shirts"],
	["polo", "Apparel & Accessories > Clothing > Shirts > Polos"],
	["dress shirt", "Apparel & Accessories > Clothing > Shirts > Dress Shirts"],
	["shirt", "Apparel & Accessories > Clothing > Shirts"],
	["hoodie", "Apparel & Accessories > Clothing > Sweatshirts & Hoodies"],
	["sweatshirt", "Apparel & Accessories > Clothing > Sweatshirts & Hoodies"],
	["sweater", "Apparel & Accessories > Clothing > Sweaters"],
	["jacket", "Apparel & Accessories > Clothing > Outerwear > Coats & Jackets"],
	["coat", "Apparel & Accessories > Clothing > Outerwear > Coats & Jackets"],
	["jeans", "Apparel & Accessories > Clothing > Pants > Jeans"],
	["pants", "Apparel & Accessories > Clothing > Pants"],
	["trousers", "Apparel & Accessories > Clothing > Pants"],
	["shorts", "Apparel & Accessories > Clothing > Shorts"],
	["skirt", "Apparel & Accessories > Clothing > Skirts"],
	["dress", "Apparel & Accessories > Clothing > Dresses"],
	["leggings", "Apparel & Accessories > Clothing > Pants > Leggings"],
	["socks", "Apparel & Accessories > Clothing > Underwear & Socks > Socks"],
	["bra", "Apparel & Accessories > Clothing > Underwear & Socks > Bras"],
	["swimsuit", "Apparel & Accessories > Clothing > Swimwear"],
	["running shoes", "Apparel & Accessories > Shoes > Athletic Shoes"],
	["sneakers", "Apparel & Accessories > Shoes > Athletic Shoes"],
	["boots", "Apparel & Accessories > Shoes > Boots"],
	["sandals", "Apparel & Accessories > Shoes > Sandals"],
	["shoes", "Apparel & Accessories > Shoes"],
	["handbag", "Apparel & Accessories > Handbags & Wallets > Handbags"],
	["backpack", "Luggage & Bags > Backpacks"],
	["wallet", "Apparel & Accessories > Handbags & Wallets > Wallets"],
	["watch", "Apparel & Accessories > Jewelry > Watches"],
	["necklace", "Apparel & Accessories > Jewelry > Necklaces"],
	["earrings", "Apparel & Accessories > Jewelry > Earrings"],
	["ring", "Apparel & Accessories > Jewelry > Rings"],
	["bracelet", "Apparel & Accessories > Jewelry > Bracelets"],
	["sunglasses", "Apparel & Accessories > Eyewear > Sunglasses"],
	["hat", "Apparel & Accessories > Clothing Accessories > Hats"],
	["cap", "Apparel & Accessories > Clothing Accessories > Hats"],
	["scarf", "Apparel & Accessories > Clothing Accessories > Scarves & Shawls"],
	["belt", "Apparel & Accessories > Clothing Accessories > Belts"],
	["smartphone", "Electronics > Communications > Telephony > Mobile Phones"],
	["phone case", "Electronics > Electronics Accessories > Mobile Phone Accessories > Mobile Phone Cases"],
	["headphones", "Electronics > Audio > Audio Components > Headphones"],
	["earbuds", "Electronics > Audio > Audio Components > Headphones"],
	["speaker", "Electronics > Audio > Audio Components > Speakers"],
	["laptop", "Electronics > Computers > Laptops"],
	["keyboard", "Electronics > Computer Accessories > Keyboards"],
	["mouse", "Electronics > Computer Accessories > Mice & Trackballs"],
	["charger", "Electronics > Electronics Accessories > Power > Chargers"],
	["camera", "Cameras & Optics > Cameras"],
	["desk lamp", "Home & Garden > Lighting > Lamps > Table Lamps"],
	["lamp", "Home & Garden > Lighting > Lamps"],
	["candle", "Home & Garden > Decor > Home Fragrances > Candles"],
	["mug", "Home & Garden > Kitchen & Dining > Tableware > Drinkware > Mugs"],
	["bottle", "Home & Garden > Kitchen & Dining > Food & Beverage Carriers > Water Bottles"],
	["pillow", "Home & Garden > Linens & Bedding > Bedding > Pillows"],
	["blanket", "Home & Garden > Linens & Bedding > Bedding > Blankets"],
	["towel", "Home & Garden > Linens & Bedding > Towels"],
	["rug", "Home & Garden > Decor > Rugs"],
	["chair", "Furniture > Chairs"],
	["desk", "Furniture > Desks"],
	["table", "Furniture > Tables"],
	["coffee", "Food, Beverages & Tobacco > Beverages > Coffee"],
	["tea", "Food, Beverages & Tobacco > Beverages > Tea & Infusions"],
	["chocolate", "Food, Beverages & Tobacco > Food Items > Candy & Chocolate"],
	["protein powder", "Health & Beauty > Health Care > Fitness & Nutrition > Nutritional Supplements"],
	["supplement", "Health & Beauty > Health Care > Fitness & Nutrition > Nutritional Supplements"],
	["shampoo", "Health & Beauty > Personal Care > Hair Care > Shampoo & Conditioner"],
	["serum", "Health & Beauty > Personal Care > Cosmetics > Skin Care"],
	["moisturizer", "Health & Beauty > Personal Care > Cosmetics > Skin Care"],
	["lipstick", "Health & Beauty > Personal Care > Cosmetics > Makeup > Lip Makeup"],
	["perfume", "Health & Beauty > Personal Care > Cosmetics > Perfume & Cologne"],
	["soap", "Health & Beauty > Personal Care > Bath & Body > Bar Soap"],
	["yoga mat", "Sporting Goods > Exercise & Fitness > Yoga & Pilates > Yoga & Pilates Mats"],
	["dumbbell", "Sporting Goods > Exercise & Fitness > Free Weights"],
	["bicycle", "Sporting Goods > Outdoor Recreation > Cycling > Bicycles"],
	["tent", "Sporting Goods > Outdoor Recreation > Camping & Hiking > Tents"],
	["toy", "Toys & Games > Toys"],
	["puzzle", "Toys & Games > Puzzles"],
	["board game", "Toys & Games > Games > Board Games"],
	["notebook", "Office Supplies > General Office Supplies > Paper Products > Notebooks & Notepads"],
	["pen", "Office Supplies > General Office Supplies > Writing & Drawing Instruments > Pens & Pencils"],
	["sticker", "Office Supplies > General Office Supplies > Labels & Tags"],
	["poster", "Home & Garden > Decor > Artwork > Posters, Prints & Visual Artwork"],
	["print", "Home & Garden > Decor > Artwork > Posters, Prints & Visual Artwork"],
	["dog", "Animals & Pet Supplies > Pet Supplies > Dog Supplies"],
	["cat", "Animals & Pet Supplies > Pet Supplies > Cat Supplies"],
]

// Categories that are too broad to be useful in a product feed.
export const GENERIC_CATEGORIES = new Set([
	"clothing",
	"apparel",
	"accessories",
	"electronics",
	"home",
	"home & garden",
	"beauty",
	"health & beauty",
	"food",
	"other",
	"misc",
	"miscellaneous",
	"general",
	"uncategorized",
	"default",
	"all",
	"products",
	"shop",
	"sale",
	"new",
	"featured",
])
